version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock_db # Connect to MySQL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Taubala!23
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Taubala!23
      MYSQL_DATABASE: stock_db # Create a stockdb database
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data
    networks:
      - my-network

networks:
  my-network:
    external: true # Use the shared network with frontend

volumes:
  mysql-data: # Docker volume for persistent MySQL data
